apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/multicluster-engine.multicluster-engine: ""
  name: multicluster-engine
  namespace: multicluster-engine
spec:
  channel: stable-2.1
  installPlanApproval: Automatic
  name: multicluster-engine
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: multicluster-engine.v2.1.2
